### PR TITLE
Added 32-bit Build Script

### PR DESCRIPTION
**Pull request by TheUltimateKeval**

### CODE REVIEW

**Comment by GitCatAdv** [comment]
same as #15

**Comment by giantninja908** [comment]
Add 32bit for other platforms as well

**Comment by BlackFire6933** [comment]
> Add 32bit for other platforms as well

Added Linux 32 bit 
https://girhub.com/BlackFire6933/JANREX/

**Comment by BlackFire6933** [comment]
There is no point in for Mac to have 32 bit app because Apple dropped support

**Comment by giantninja908** [comment]
Ight

**Pull request closed without merging**
